namespace LgTvConnect.IpControl;

public enum IpControlKey
{
    Exit = 0,
    ChannelUp = 1,
    ChannelDown = 2,
    VolumeUp = 3,
    VolumeDown = 4,
    ArrowRight = 5,
    ArrowLeft = 6,
    VolumeMute = 7,
    DeviceInput = 8,
    SleepReserve = 9,
    LiveTv = 10,
    PreviousChannel = 11,
    FavoriteChannel = 12,
    Teletext = 13,
    TeletextOption = 14,
    ReturnBack = 15,
    AvMode = 16,
    CaptionSubtitle = 17,
    ArrowUp = 18,
    ArrowDown = 19,
    MyApp = 20,
    SettingMenu = 21,
    Ok = 22,
    QuickMenu = 23,
    VideoMode = 24,
    AudioMode = 25,
    ChannelList = 26,
    BlueButton = 27,
    YellowButton = 28,
    GreenButton = 29,
    RedButton = 30,
    AspectRatio = 31,
    AudioDescription = 32,
    ProgrammOrder = 33,
    UserGuide = 34,
    SmartHome = 35,
    SimpleLink = 36,
    FastForward = 37,
    Rewind = 38,
    ProgrammingInfo = 39,
    ProgramGuide = 40,
    Play = 41,
    SlowPlay = 42,
    SoccerScreen = 43,
    Reord = 44,
    Autoconfig = 45,
    App = 46,
    ScreenBright = 47,
    Number0 = 48,
    Number1 = 49,
    Number2 = 50,
    Number3 = 51,
    Number4 = 52,
    Number5 = 53,
    Number6 = 54,
    Number7 = 55,
    Number8 = 56,
    Number9 = 57
}

public static class IpControlKeyExtensions
{
    public static string ToCode(this IpControlKey key)
    {
        return key switch
        {
            IpControlKey.Exit => "exit",
            IpControlKey.ChannelUp => "channelup",
            IpControlKey.ChannelDown => "channeldown",
            IpControlKey.VolumeUp => "volumeup",
            IpControlKey.VolumeDown => "volumedown",
            IpControlKey.ArrowRight => "arrowright",
            IpControlKey.ArrowLeft => "arrowleft",
            IpControlKey.VolumeMute => "volumemute",
            IpControlKey.DeviceInput => "deviceinput",
            IpControlKey.SleepReserve => "sleepreserve",
            IpControlKey.LiveTv => "livetv",
            IpControlKey.PreviousChannel => "previouschannel",
            IpControlKey.FavoriteChannel => "favoritechannel",
            IpControlKey.Teletext => "teletext",
            IpControlKey.TeletextOption => "teletextoption",
            IpControlKey.ReturnBack => "returnback",
            IpControlKey.AvMode => "avmode",
            IpControlKey.CaptionSubtitle => "captionsubtitle",
            IpControlKey.ArrowUp => "arrowup",
            IpControlKey.ArrowDown => "arrowdown",
            IpControlKey.MyApp => "myapp",
            IpControlKey.SettingMenu => "settingmenu",
            IpControlKey.Ok => "ok",
            IpControlKey.QuickMenu => "quickmenu",
            IpControlKey.VideoMode => "videomode",
            IpControlKey.AudioMode => "audiomode",
            IpControlKey.ChannelList => "channellist",
            IpControlKey.BlueButton => "bluebutton",
            IpControlKey.YellowButton => "yellowbutton",
            IpControlKey.GreenButton => "greenbutton",
            IpControlKey.RedButton => "redbutton",
            IpControlKey.AspectRatio => "aspectratio",
            IpControlKey.AudioDescription => "audiodescription",
            IpControlKey.ProgrammOrder => "programmorder",
            IpControlKey.UserGuide => "userguide",
            IpControlKey.SmartHome => "smarthome",
            IpControlKey.SimpleLink => "simplelink",
            IpControlKey.FastForward => "fastforward",
            IpControlKey.Rewind => "rewind",
            IpControlKey.ProgrammingInfo => "programminfo",
            IpControlKey.ProgramGuide => "programguide",
            IpControlKey.Play => "play",
            IpControlKey.SlowPlay => "slowplay",
            IpControlKey.SoccerScreen => "soccerscreen",
            IpControlKey.Reord => "reord",
            IpControlKey.Autoconfig => "autoconfig",
            IpControlKey.App => "app",
            IpControlKey.ScreenBright => "screenbright",
            IpControlKey.Number0 => "number0",
            IpControlKey.Number1 => "number1",
            IpControlKey.Number2 => "number2",
            IpControlKey.Number3 => "number3",
            IpControlKey.Number4 => "number4",
            IpControlKey.Number5 => "number5",
            IpControlKey.Number6 => "number6",
            IpControlKey.Number7 => "number7",
            IpControlKey.Number8 => "number8",
            IpControlKey.Number9 => "number9",
            _ => throw new ArgumentOutOfRangeException(nameof(key), key, null)
        };
    }
}